apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: realworld
  labels:
    app: frontend
    component: ui
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: frontend
  type: ClusterIP