apiVersion: v1
kind: ServiceAccount
metadata:
  name: realworld-serviceaccount
  namespace: realworld
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: realworld
  name: realworld-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: realworld-rolebinding
  namespace: realworld
subjects:
- kind: ServiceAccount
  name: realworld-serviceaccount
  namespace: realworld
roleRef:
  kind: Role
  name: realworld-role
  apiGroup: rbac.authorization.k8s.io