{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mongodb
    component: database
    {{- if and .Values.monitoring.enabled .Values.monitoring.mongodb.exporter.enabled }}
    monitoring: "true"
    {{- end }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  {{- if and .Values.monitoring.enabled .Values.monitoring.mongodb.exporter.enabled }}
  - port: {{ .Values.monitoring.mongodb.exporter.port }}
    targetPort: {{ .Values.monitoring.mongodb.exporter.port }}
    name: metrics
  {{- end }}
  selector:
    app: mongodb
  clusterIP: None
{{- end }}